### ISSUE TITLE
Google Search Console " data-vocabulary.org şeması kullanımdan kaldırıldı " hatası

### ISSUE THREAD

**Issue by AndroidHaber** [kanthemes/gmedia#1]
![1hata](https://user-images.githubusercontent.com/71183802/92998563-14cf1e80-f523-11ea-9457-044bec03a29b.png)
![2hata](https://user-images.githubusercontent.com/71183802/92998565-16004b80-f523-11ea-86d6-f826a496f19a.png)
Merhabalar. Gmedia temanızı kullanıyorum . Google Search Console ' da resimde eklemiş olduğum hataları veriyor, internetten az bir araştırma ile çözümünü buldum. Çözümü için linkini bırakıyorum. 

https://dijitalpazarlamadunyasi.com/data-vocabulary-semasi-kullanimdan-kalkti/

Teşekkürler.. 👍 
İyi Çalışmalar :)

**Comment by kanthemesdev** [comment]
Merhaba,
Hemen bir güncelleme yayınladık, teşekkür ederiz.

**Comment by AndroidHaber** [comment]
teşekkürler  hocam
