### ISSUE TITLE
Tema da bazı hatalar mevcut

### ISSUE THREAD

**Issue by birsevda** [kanthemes/gmedia#3]
Öncelikle böyle bir tema için teşşekürler.

İlk hata wp admin de 
`Gmedia, Kan Themes tarafından ücretsiz paylaşılmış bir wordpress blog temasıdır. Eğer temamızdan memnunsanız aşağıdaki teşekkür et butonuna tıklayarak ürün sayfamızda kısa bir mesaj bırakabilirsiniz.

Hata bildirimi yapmak için veya tema ile alakalı sorularınız için aşağıdaki Hata Bildirimi butonuna tıklayarak bir konu başlatabilirsiniz.

Hata Bildir`

bu gitmiyor ne yaparsam yapayım.
2. hata  sitenin anasayasında son yazıları 3 yapmama rağmen butun yazıları gösteriyor sidebarda.
site: https://heyt.net

**Comment by cagriuckan** [comment]
Merhaba,

1- Aşağıdaki kodu silerek kaldırabilirsiniz.
https://github.com/kanthemes/gmedia/blob/1c29cd8945fedd30f505e2514ba3a3cbb6ca58e9/framework/Admin/includes/ot-functions.php#L388
2- "Blogun en üstüne sabitle" olarak işaretlediğiniz yazıları böyle işaretlemekten vazgeçin.
https://wordpress.org/support/article/sticky-posts/

**Comment by birsevda** [comment]
Teşşekürler elinize sağlık.
