### ISSUE TITLE
Çeşitli Değişken Hataları 

### ISSUE THREAD

**Issue by yemrek** [kanthemes/gmedia#4]
Merhabalar,

$userID
$post->ID
$category

bu tarz kodlarda temanın her yerinde hata veriyor bu php versiyonuyla mı alakalı yoksa wordpress'in güncellemesi ile mi ? Cevaplarsanız temayı editledim ama şuan kategoride yazılar gözükmüyor diğerlerini çözdüm sayılır ama onu çözemedim.

![Screenshot_12](https://user-images.githubusercontent.com/31688157/132102972-5b226164-2e5f-4f23-85b0-e03941468cd8.png)
![Screenshot_11](https://user-images.githubusercontent.com/31688157/132102973-41c4dfbe-f69b-4930-9fc0-d0416e88baed.png)

--------------------------------------

![Screenshot_14](https://user-images.githubusercontent.com/31688157/132103019-7103a0d6-89da-4dba-ba0d-f19766839096.png)
![Screenshot_13](https://user-images.githubusercontent.com/31688157/132103021-0f1db3a7-e67b-4a94-967d-cc04f63be44a.png)

**Comment by yemrek** [comment]
Yardımcı olabilir misiniz rica etsem temanın düzenlemesini kendimi geliştirmek için kullanıyorum 🙏 @cagriuckan @kanthemesdev

**Comment by devon52** [comment]
Dosyanın tam halini paylaşır mısın @yemrek

**Comment by yemrek** [comment]
> Dosyanın tam halini paylaşır mısın? @yemrek 

Dosyanın tam hali tema dosyasında ben o anlamda bir değişiklik yapmadım.

**Comment by cagriuckan** [comment]
Teşekkürler, düzeltilmiştir.
https://github.com/kanthemes/gmedia/commit/2e644cfb3190a560fd62b61facf9e73cdfd838ee
